# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
#     - name: Deploy Gatsby to AWS S3
#       uses: jonelantha/gatsby-s3-action@v1.2.0
#       with:
#         # Path to Gatsby /public directory
#         public-source-path: # optional, default is ./public/
#         # Destination S3 Bucket
#         dest-s3-bucket: ${{ secrets.S3_BUCKET }}
#         # Destination S3 Path
#         dest-s3-path: # optional
#         # Boolean, delete files on S3 not present in build (default: true)
#         sync-delete: # optional, default is true
#         # Browser cache duration (sec) for cache control headers
#         browser-cache-duration: # optional, default is 31536000
#         # CDN cache duration (sec) for cache control headers (sec)
#         cdn-cache-duration: # optional, default is 31536000
#         # Cloudfront ID to invalidate
#         cloudfront-id-to-invalidate: # optional
#         # Cloudfront Path to invalidate (optional, default: '/*')
#         cloudfront-path-to-invalidate: # optional, default is /*

